var_labels = {
  "Q_v" : "$q_v$ [g/kg]",
  "Qv" : "$q_v$ [g/kg]",
  "LWC_gm-3" : "LWC [$g m^{-3}$]" ,
  "N_drop" : "$N_{drop}$ [cm$^{-3}$]",
  "N_aerosol" : "$N_{aerosol}$ [cm$^{-3}$]",
  "N_removal" : "$N_{removal}$ [cm$^{-3}$]",
  "disp_r" : "rel. disp. of r",
  "r_mean1" : "$<r> [\mu m]$",
  "Sigma2_T" : "var. of T [K$^2$]",
  "Sigma2_Qv" :  "var. of $q_v [(g/kg)^2$]",
  "epsilon" : "$\epsilon [m^2 s^{-3}]$",
  "tot_tke" : "TKE$ [[m^2 s^{-2}]$",
  "H_flux_t" : "top heat flux [$W m^{-2}$]",
  "H_flux_b" : "bot heat flux [$W m^{-2}$]",
  "qv_flux_t" : "top $q_v$ flux [kg/kg m/s]",
  "qv_flux_b" : "bot $q_v$ flux [kg/kg m/s]",
  "T" : "T [K]",
  "rv" : "$q_v$ [g/kg]",
  "RH" : "RH",
  "RH_max" : "RH max",
  "S_drop" : "$S_{drop}$",
  "Sigma2_S" : "$S$ variance",
  "Sigma2_S_drop" : "$S_{drop}$ variance",
  "N_c" : "$N_c$ [cm$^{-3}$]",
  "r_mean1" : "$<r>$",
  "sgs_tke" : 'SGS TKE (Smagorinsky) [m$^{2}$ s$^{-2}$]',
  "sgs_tke_sd" : 'SGS TKE (Super-droplets) [m$^{2}$ s$^{-2}$]',
  "lwp" : 'LWP [g m$^{-2}$]',
  "rwp" : 'RWP [g m$^{-2}$]',
  "surf_precip" : 'Surf. precip. [mm/day]',
  "acc_precip" : 'Acc. precip. [mm]',
  "cl_nc" : '$N_c$ [cm$^{-3}$]',
#  "cl_nr" : '$N_{r>25\mu m}$ [cm$^{-3}$]',
  "cl_nr" : '$N_{r}$ [cm$^{-3}$]',
  "cl_gccn_conc" : '$N_{GCCN}$ [cm$^{-3}$]',
  "thl" : r'$\theta_l$ [K]',
  "00rtot" : '$q_{t}$ [g/kg]',
  "rliq" : '$q_{l}$ [g/kg]',
  "clfrac" : 'Cloud fraction',
  "cloud_cover" : 'Cloud cover',
  "cloud_cover_dycoms" : 'Cloud cover',
  "prflux" : 'Precip. flux [W m$^{-2}$]',
  "wvar" : r'Var$\left(w\right)$ [m$^2$ s$^{-2}$]',
  "w3rd" : 'Third mom. of $w$ [m$^3$ s$^{-3}$]',
  "sat_RH" : 'Supersaturation [\%]',
  "rad_flx" : 'radiative flux [W m$^{-2}$]',
  "cl_nc_zoom" : '$N_c$ [cm$^{-3}$]',
  "base_prflux_vs_clhght" : 'pr. flux at column base [W m$^{-2}$]',
  "base_prflux_vs_clhght number of occurances" : 'number of occurances',
  "er" : 'Entrain. rate [cm s$^{-1}$]',
  "wvarmax" : 'Max. $w$ var. [m$^{2}$ s$^{-2}$]',
  "cloud_base_dycoms" : 'Cloud base [m]',
  "min_cloud_base" : 'Lowest cloud base [m]',
  "inversion_height_rico" : 'Inversion height [m]',
  "gccn_rw_cl" : '$<r>$ of GCCN droplets [um]',
  "non_gccn_rw_cl" : '$<r>$ of CCN droplets [um]',
  "clb_bigrain_mean_rd" : '$<r_d>$ of (r$>$40um) @ clbase [m]',
  "clb_bigrain_mean_kappa" : '$\kappa$ of (r$>$40um) @ clbase',
  "clb_bigrain_mean_conc" : 'conc. of (r$>$40um) @ clbase [1/cc]',
  "clb_bigrain_mean_inclt" : 'time since act. of (r$>$40um) @ clbase [s]',
  "clb_bigrain_mean_gccn_fraction" : 'frac. of (r$>$40um) on gccn @ clbase',
  "cl_acnv25" : 'acnv. rate [g m$^{-3}$ d$^{-1}$]',
  "cl_accr25" : 'accr. rate [g m$^{-3}$ d$^{-1}$]',
  "cl_avg_supersat" : '$<S>$ in cloud [\%]',
  "cl_avg_th" : '$<\\theta>$ in cloud [K]',
  "cl_avg_rv" : '$<r_v>$ in cloud [1]',
  "cl_avg_cloud_meanr" : '$<r>$ of cloud droplets in cloud [um]',
  "cl_avg_cloud_stddevr" : '$\sigma(r)$ of cloud droplets in cloud [um]',
  "sd_conc" : '$<SD>$',
  "surf_flux_latent"   : 'latent surface flux [W/m$^2$]',
  "surf_flux_sensible" : 'sensible surface flux [W/m$^2$]',
}


labeldict = {
 0 : "(a)",
 1 : "(b)",
 2 : "(c)",
 3 : "(d)",
 4 : "(e)",
 5 : "(f)",
 6 : "(g)",
 7 : "(h)",
 8 : "(i)",
 9 : "(j)",
 10 : "(k)",
 11 : "(l)",
 12 : "(m)",
 13 : "(n)",
 14 : "(o)",
 15 : "(p)",
 16 : "(q)",
 17 : "(r)",
 18 : "(s)",
 19 : "(t)",
}
